### ISSUE TITLE
CLI for ease of use

### ISSUE THREAD

**Issue by michaelmior** [romansky/dom-to-semantic-markdown#1]
It would be really helpful if this had a CLI where I could give the path to an HTML file (or just pipe it in) and then get markdown as output without having to write a wrapper to do this.

**Comment by romansky** [comment]
Hi @michaelmior, would love to support this use case!
Just pushed some code to allow you to do that-

https://github.com/romansky/dom-to-semantic-markdown/blob/main/examples/cli/README.md

Can you try it out and let me know if this answers your use case?

**Comment by michaelmior** [comment]
Thanks! Would be great if this was possible to run with `npx` without manually installing, but I think this should work :)

**Comment by romansky** [comment]
Ah I see, indeed way better DX with `npx`.. working on adding it :)

**Comment by romansky** [comment]
You can use `npx` now!

```shell
> npx d2m@latest -h                    
Usage: d2m [options]

Convert DOM to Semantic Markdown

Options:
  -V, --version        output the version number
  -i, --input <file>   Input HTML file
  -o, --output <file>  Output Markdown file
  -e, --extract-main   Extract main content
  -u, --url <url>      URL to fetch HTML content from
  -h, --help           display help for command

>  npx d2m@latest -u https://example.com

# Example Domain

This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.

 [More information...](https://www.iana.org/domains/example)

```
