### ISSUE TITLE
Anchors on div blocks

### ISSUE THREAD

**Issue by david8z** [romansky/dom-to-semantic-markdown#10]
How should anchors in div blocks be formatted?

```javascript
import { convertHtmlToMarkdown } from "dom-to-semantic-markdown";

const html = '<a href="/security"><div><div>Block 1</div><div>Block 2</div><div>Hello</div></a>'

convertHtmlToMarkdown(html)
```

Outputs:

```markdown
[](file:///security) <a href="file:///security">   Block 1   Block 2   Hello</a>
```

Unsure if this is an actual issue but I feel the current approach kind of breaks the inner element structure of the anchors.

**Comment by romansky** [comment]
Hi @david8z, without taking into account any CSS, `div` elements would be considered blocks (vs inline elements). Considering responsive design, flex and what not.. by themselves, `div`s don't provide any "semantic" indication like a `<p>` element would in terms of breaking lines. So we ignore them during the parsing right now.. 

Can you think of a generalizable approach to parsing these that improves current logic somehow?

**Comment by david8z** [comment]
Hey @romansky first thanks for the lib so cool.

My concern is more on teh direction that markdown does not render elements inside html blocks.

> So if we render the output of this image in a markdown visualizer it will not show the headings, Does that makes sense 🤔 

![image](https://github.com/user-attachments/assets/80ff9038-6642-4cd2-baf1-992c7ad58908)

**Comment by romansky** [comment]
Thanks for the feedback!

This depends on the Markdown renderer, it looks like intellij Markdown renderer words fine as well as Github's

```markdown
[](/security) <a href="/security">
# Block 1

## Block 2

### Hello

</a>
```
(pasting as Markdown below)
[](/security) <a href="/security">
# Block 1

## Block 2

### Hello

</a>

**Comment by david8z** [comment]
Oh closing issue then 👍

**Comment by david8z** [comment]
Missconception on how elements should be shown inside html tags.
