### ISSUE TITLE
FEATURE: Need support for non Node.js environments (Browser Extensions).

### ISSUE THREAD

**Issue by MODSetter** [romansky/dom-to-semantic-markdown#14]
Hi,
I use **dom-to-semantic-markdown** in a browser extension at https://github.com/MODSetter/SurfSense

I want to move dom processing to service worker so whole extension scripts can have access to it. (Currently only popup script have its access and it can have access to DomParser API)

Extension Background Scripts/service workers doesn't work on Node.js env. It doesn't have access to DomParser API.

Now I have tried these till now:

Without overrideDOMParser :
err:
![without](https://github.com/user-attachments/assets/d2bd9b01-2beb-40d6-911e-62f07974a899)

With JSDOM:
func:
![funcjsdom](https://github.com/user-attachments/assets/0d0fdc91-c252-446c-83c8-ae7772e3df56)

err:
![withjsdom](https://github.com/user-attachments/assets/4086d21b-13bf-488d-9e13-82bff6b6946f)

With Linkedom (Global Node vars defined)  :
func:
![funclinkedom](https://github.com/user-attachments/assets/d8a8a730-7716-44d9-9719-9216e3ba2082)

err:
![withlinkedom](https://github.com/user-attachments/assets/e48f24f7-d312-493e-ae6b-b9c61270d193)

How should I try to solve this?

**Comment by romansky** [comment]
Hi @MODSetter !

It seems like for the most part the DOMParser is working but the content you are handling might have some properties missing, I fixed this in v1.2.5, can you try and report back?

**Comment by MODSetter** [comment]
> Hi @MODSetter !
> 
> It seems like for the most part the DOMParser is working but the content you are handling might have some properties missing, I fixed this in v1.2.5, can you try and report back?

Tried the new version. Getting this now:
![newerr](https://github.com/user-attachments/assets/77b5b791-2f6b-4f2c-9950-af2de76fb319)

**Comment by romansky** [comment]
@MODSetter thanks for the bug report, the issue was with trying to do `escapeMarkdownCharacters` on a null attribute.. please try again with v1.2.7 🙏

**Comment by MODSetter** [comment]
> @MODSetter thanks for the bug report, the issue was with trying to do `escapeMarkdownCharacters` on a null attribute.. please try again with v1.2.7 🙏

Hi @romansky 
Its working now ☺️ . Thanks for the quick fixes it really saved me a lot of time. Nice work 👍
