### ISSUE TITLE
Remove repeated blank lines from the output

### ISSUE THREAD

**Issue by psugihara** [romansky/dom-to-semantic-markdown#18]
Cool library! Noticed a small issue that seems easy to fix. The output contains a lot of extra newlines. Think this would be a pretty simple `replace(/\n{2,}/g, '\n')`?

As a test case/example here's a snippet from my output:

```
  View all



---

---


## Contact
```

**Comment by romansky** [comment]
@psugihara would be great to have a test case for this, do you have a link / html to show the issue?

Generally would prefer to avoid a global replace like this.. though if there is no structural logic I can come up with, then let's give this a go :)

**Comment by psugihara** [comment]
Sure. here's a super random example: `npx d2m@latest -u https://www.linkedin.com -o li.md` and a random excerpt of the output

```



---

---



<-header->


</-header->
No more previous content
- ## Let the right people know you’re open to work
```

**Comment by psugihara** [comment]
Got it, no worries. I'll do the post-processing for my use-case.
