### ISSUE TITLE
nicer support for openai docs?

### ISSUE THREAD

**Issue by tarasglek** [romansky/dom-to-semantic-markdown#5]
This library seems to work really well, but it fails to process openai code snippets

I used https://github.com/gildas-lormeau/SingleFile to download https://platform.openai.com/docs/api-reference

```
npx d2m@latest -i ~/Downloads/API\ Reference\ -\ OpenAI\ API\ \(7_25_2024\ 10_21_36\ AM\).html > reference.md
```

This results in really unusable code blocks:
<img width="1327" alt="image" src="https://github.com/user-attachments/assets/bc1b8da6-24f3-4470-9258-b920ecd5ad7e">

I would switch my https://markdown.download to this in a heartbeat if it would handle code blocks like this, seems to handle rest of the docs perfectly

**Comment by romansky** [comment]
Thanks for the bug report!

I fixed the handling of the code blocks and added some logic to extract the language.
